### ISSUE TITLE
Black screen on recorded videos in League of legends

### ISSUE THREAD

**Issue by geoffho** [lulzsun/RePlaysTV#34] opened 2020-04-22 15:25 UTC
I am experiencing a black screen with audio on my recorded League of legends replays.
I am unable to rollback my windows10 updates because it has been over 10days since the update. What would solve this issue?

**Comment by UdonBdon** [comment] 2020-04-29 08:36
Same, I recently reinstalled replays and now i'm getting a black screen for just league of legends.

**Comment by lulzsun** [comment] 2020-05-11 06:21
There is no fix if you can't rollback the update. You will have to wait until major changes and development to RePlays.

Closing this as it is a duplicate of #20

**Closed as completed by lulzsun** 2020-05-11 06:21 UTC
Labels: duplicate
